### PR TITLE
neighbors setting to fix wet soil

### PR DESCRIPTION
**Pull request by ghost**
Sorry I did some tidying up in my github reps. 
So I remade the changes in a new branch. I'm closing the old PR and making this one

This add a "neighbors" setting in each difficulty level to configure blocks on wich plants grows. 
For now it is set to wet_soil and desert_sand_soil_wet everywhere.

>  sofar commented on 22 Oct 2016
> 
> Shall we just fix it instead? I intended this to only grow on wet soil. I can see that allowing dry soil for growth for some plants (e.g. potatoes) but that's unlikely anyway.
> 
> So, let's just make it grow on wet soil?

It is now set to wet soil and wet desert sand soil but I kept the use of a global setting because : 
- This make a default variable usable in new plants 
- It's easyly editable to follow change of farming or default (e.g. adding desert_sand_soil_wet was only a 3 line edit in init.lua and if something else like that or a future wet_soil group appear it will be just as easy to implement it)
- It is still possible to  configure plants individualy
- It is now possible to use soil type to adjust difficulty level (e.g. easy setting could be any node of group:soil, or difficult could only allow wet soil and not wet sand soil)

### CODE REVIEW

**Comment by ghost** [comment]
I notice I wrote wet soil instead of soil_wet in the init.lua file ! It is now corrected

**Comment by sofar** [comment]
So, this makes all crops grow on wet sand, which I don't like. Ideally we move the neighbor to the actual plant def.

I've been thinking of rewriting this code to make it more easy. It's about time to redo some of the code because it's too handcrafted, and I never sat down and cleaned it up.

**Comment by ghost** [comment]
It would be very easy to change it back to only wet soil (that was the point of adding neighbors to the main setting table)
But neighbor can also still be modified individually in each plant def
Since wet desert sand soil was recently introduced I thought, why not add it to the common tables. 

I'll keep an eye out for the rewritting.

**Comment by sofar** [comment]
reasonable time elapsed, closing due to no resonse. reopen if you are working on it again.

**Pull request closed without merging**
